apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postman-clone.api.fullname" . }}-env
  namespace: {{ include "postman-clone.namespace" . }}
  labels:
    {{- include "postman-clone.labels" . | nindent 4 }}
    {{- include "postman-clone.api.selectorLabels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  PORT: {{ .Values.api.env.PORT | quote }}
  APP_ORIGIN: {{ .Values.api.env.APP_ORIGIN | quote }}
  DB_HOST: {{ include "postman-clone.databaseHost" . | quote }}
  DB_PORT: {{ include "postman-clone.databasePort" . | quote }}
  DB_NAME: {{ include "postman-clone.databaseName" . | quote }}
  DB_SYNCHRONIZE: {{ .Values.api.env.DB_SYNCHRONIZE | quote }}
  SESSION_COOKIE_NAME: {{ .Values.api.env.SESSION_COOKIE_NAME | quote }}
  {{- if .Values.api.env.DOCKER_LOCALHOST_ALIAS }}
  DOCKER_LOCALHOST_ALIAS: {{ .Values.api.env.DOCKER_LOCALHOST_ALIAS | quote }}
  {{- end }}
