{{- if .Values.api.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "postman-clone.api.fullname" . }}
  namespace: {{ include "postman-clone.namespace" . }}
  labels:
    {{- include "postman-clone.labels" . | nindent 4 }}
    {{- include "postman-clone.api.selectorLabels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.api.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.api.podDisruptionBudget.minAvailable }}
  {{- else if .Values.api.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.api.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "postman-clone.api.selectorLabels" . | nindent 6 }}
{{- end }}
