{{- if not .Values.api.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postman-clone.api.fullname" . }}
  namespace: {{ include "postman-clone.namespace" . }}
  labels:
    {{- include "postman-clone.labels" . | nindent 4 }}
    {{- include "postman-clone.api.selectorLabels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  DB_USER: {{ .Values.api.secrets.dbUser | b64enc | quote }}
  DB_PASSWORD: {{ .Values.api.secrets.dbPassword | b64enc | quote }}
{{- end }}
