{{- if .Values.web.nginxConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postman-clone.web.fullname" . }}-nginx
  namespace: {{ include "postman-clone.namespace" . }}
  labels:
    {{- include "postman-clone.labels" . | nindent 4 }}
    {{- include "postman-clone.web.selectorLabels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  default.conf: |
{{ tpl .Values.web.nginxConfig . | indent 4 }}
{{- end }}
