apiVersion: v1
kind: Service
metadata:
  name: {{ include "postman-clone.web.fullname" . }}
  namespace: {{ include "postman-clone.namespace" . }}
  labels:
    {{- include "postman-clone.labels" . | nindent 4 }}
    {{- include "postman-clone.web.selectorLabels" . | nindent 4 }}
  {{- with merge (.Values.web.service.annotations | default dict) (.Values.commonAnnotations | default dict) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "postman-clone.web.selectorLabels" . | nindent 4 }}
